/* tslint:disable */
/* eslint-disable */
/**
 * MathGrass
 * This is the OpenAPI specification for MathGrass
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: andreas.domanowski@tu-dresden.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunStaticAssessment200Response
 */
export interface RunStaticAssessment200Response {
    /**
     * 
     * @type {boolean}
     * @memberof RunStaticAssessment200Response
     */
    isAssessmentCorrect: boolean;
}

/**
 * Check if a given object implements the RunStaticAssessment200Response interface.
 */
export function instanceOfRunStaticAssessment200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "isAssessmentCorrect" in value;

    return isInstance;
}

export function RunStaticAssessment200ResponseFromJSON(json: any): RunStaticAssessment200Response {
    return RunStaticAssessment200ResponseFromJSONTyped(json, false);
}

export function RunStaticAssessment200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunStaticAssessment200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isAssessmentCorrect': json['isAssessmentCorrect'],
    };
}

export function RunStaticAssessment200ResponseToJSON(value?: RunStaticAssessment200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isAssessmentCorrect': value.isAssessmentCorrect,
    };
}

