/* tslint:disable */
/* eslint-disable */
/**
 * MathGrass
 * This is the OpenAPI specification for MathGrass
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: andreas.domanowski@tu-dresden.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunStaticAssessmentRequest
 */
export interface RunStaticAssessmentRequest {
    /**
     * 
     * @type {string}
     * @memberof RunStaticAssessmentRequest
     */
    answer: string;
}

/**
 * Check if a given object implements the RunStaticAssessmentRequest interface.
 */
export function instanceOfRunStaticAssessmentRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "answer" in value;

    return isInstance;
}

export function RunStaticAssessmentRequestFromJSON(json: any): RunStaticAssessmentRequest {
    return RunStaticAssessmentRequestFromJSONTyped(json, false);
}

export function RunStaticAssessmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunStaticAssessmentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'answer': json['answer'],
    };
}

export function RunStaticAssessmentRequestToJSON(value?: RunStaticAssessmentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'answer': value.answer,
    };
}

