/* tslint:disable */
/* eslint-disable */
/**
 * MathGrass
 * This is the OpenAPI specification for MathGrass
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: andreas.domanowski@tu-dresden.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskTopic
 */
export interface TaskTopic {
    /**
     * 
     * @type {number}
     * @memberof TaskTopic
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskTopic
     */
    label?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof TaskTopic
     */
    tasks?: Array<number>;
}

/**
 * Check if a given object implements the TaskTopic interface.
 */
export function instanceOfTaskTopic(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TaskTopicFromJSON(json: any): TaskTopic {
    return TaskTopicFromJSONTyped(json, false);
}

export function TaskTopicFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskTopic {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'tasks': !exists(json, 'tasks') ? undefined : json['tasks'],
    };
}

export function TaskTopicToJSON(value?: TaskTopic | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'label': value.label,
        'tasks': value.tasks,
    };
}

