/* tslint:disable */
/* eslint-disable */
/**
 * MathGrass
 * This is the OpenAPI specification for MathGrass
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: andreas.domanowski@tu-dresden.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskCollection
 */
export interface TaskCollection {
    /**
     * 
     * @type {number}
     * @memberof TaskCollection
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskCollection
     */
    label?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof TaskCollection
     */
    tasks?: Array<number>;
}

/**
 * Check if a given object implements the TaskCollection interface.
 */
export function instanceOfTaskCollection(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TaskCollectionFromJSON(json: any): TaskCollection {
    return TaskCollectionFromJSONTyped(json, false);
}

export function TaskCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskCollection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'tasks': !exists(json, 'tasks') ? undefined : json['tasks'],
    };
}

export function TaskCollectionToJSON(value?: TaskCollection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'label': value.label,
        'tasks': value.tasks,
    };
}

