/* tslint:disable */
/* eslint-disable */
/**
 * MathGrass
 * This is the OpenAPI specification for MathGrass
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: andreas.domanowski@tu-dresden.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Vertex
 */
export interface Vertex {
    /**
     * 
     * @type {number}
     * @memberof Vertex
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Vertex
     */
    x: number;
    /**
     * 
     * @type {number}
     * @memberof Vertex
     */
    y: number;
    /**
     * 
     * @type {string}
     * @memberof Vertex
     */
    label?: string;
}

/**
 * Check if a given object implements the Vertex interface.
 */
export function instanceOfVertex(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "x" in value;
    isInstance = isInstance && "y" in value;

    return isInstance;
}

export function VertexFromJSON(json: any): Vertex {
    return VertexFromJSONTyped(json, false);
}

export function VertexFromJSONTyped(json: any, ignoreDiscriminator: boolean): Vertex {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'x': json['x'],
        'y': json['y'],
        'label': !exists(json, 'label') ? undefined : json['label'],
    };
}

export function VertexToJSON(value?: Vertex | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'x': value.x,
        'y': value.y,
        'label': value.label,
    };
}

