/* tslint:disable */
/* eslint-disable */
/**
 * MathGrass
 * This is the OpenAPI specification for MathGrass
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: andreas.domanowski@tu-dresden.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists } from '../runtime';
import { VertexDTOFromJSON, VertexDTOToJSON, } from './VertexDTO';
/**
 * Check if a given object implements the EdgeDTO interface.
 */
export function instanceOfEdgeDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "firstVertex" in value;
    isInstance = isInstance && "secondVertex" in value;
    return isInstance;
}
export function EdgeDTOFromJSON(json) {
    return EdgeDTOFromJSONTyped(json, false);
}
export function EdgeDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'firstVertex': VertexDTOFromJSON(json['firstVertex']),
        'secondVertex': VertexDTOFromJSON(json['secondVertex']),
        'label': !exists(json, 'label') ? undefined : json['label'],
    };
}
export function EdgeDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'firstVertex': VertexDTOToJSON(value.firstVertex),
        'secondVertex': VertexDTOToJSON(value.secondVertex),
        'label': value.label,
    };
}
