/* tslint:disable */
/* eslint-disable */
/**
 * MathGrass
 * This is the OpenAPI specification for MathGrass
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: andreas.domanowski@tu-dresden.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists } from '../runtime';
import { EdgeDTOFromJSON, EdgeDTOToJSON, } from './EdgeDTO';
import { LabelDTOFromJSON, LabelDTOToJSON, } from './LabelDTO';
import { VertexDTOFromJSON, VertexDTOToJSON, } from './VertexDTO';
/**
 * Check if a given object implements the GraphDTO interface.
 */
export function instanceOfGraphDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "edges" in value;
    isInstance = isInstance && "vertices" in value;
    return isInstance;
}
export function GraphDTOFromJSON(json) {
    return GraphDTOFromJSONTyped(json, false);
}
export function GraphDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': json['id'],
        'labels': !exists(json, 'labels') ? undefined : (json['labels'].map(LabelDTOFromJSON)),
        'edges': (json['edges'].map(EdgeDTOFromJSON)),
        'vertices': (json['vertices'].map(VertexDTOFromJSON)),
    };
}
export function GraphDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'labels': value.labels === undefined ? undefined : (value.labels.map(LabelDTOToJSON)),
        'edges': (value.edges.map(EdgeDTOToJSON)),
        'vertices': (value.vertices.map(VertexDTOToJSON)),
    };
}
