/* tslint:disable */
/* eslint-disable */
/**
 * MathGrass
 * This is the OpenAPI specification for MathGrass
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: andreas.domanowski@tu-dresden.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GraphDTOFromJSON, GraphDTOToJSON, } from './GraphDTO';
import { QuestionDTOFromJSON, QuestionDTOToJSON, } from './QuestionDTO';
/**
 * Check if a given object implements the TaskDTO interface.
 */
export function instanceOfTaskDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "graph" in value;
    isInstance = isInstance && "question" in value;
    return isInstance;
}
export function TaskDTOFromJSON(json) {
    return TaskDTOFromJSONTyped(json, false);
}
export function TaskDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': json['id'],
        'graph': GraphDTOFromJSON(json['graph']),
        'question': QuestionDTOFromJSON(json['question']),
    };
}
export function TaskDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'graph': GraphDTOToJSON(value.graph),
        'question': QuestionDTOToJSON(value.question),
    };
}
