/* tslint:disable */
/* eslint-disable */
/**
 * MathGrass
 * This is the OpenAPI specification for MathGrass
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: andreas.domanowski@tu-dresden.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists } from '../runtime';
/**
 * Check if a given object implements the TaskCollectionDTO interface.
 */
export function instanceOfTaskCollectionDTO(value) {
    let isInstance = true;
    return isInstance;
}
export function TaskCollectionDTOFromJSON(json) {
    return TaskCollectionDTOFromJSONTyped(json, false);
}
export function TaskCollectionDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'tasks': !exists(json, 'tasks') ? undefined : json['tasks'],
    };
}
export function TaskCollectionDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'label': value.label,
        'tasks': value.tasks,
    };
}
